import type { FieldSpec } from '../components/wizard/FieldControl'
import type { SectionKey } from '../types/wizard'

type Spec = FieldSpec

export const fieldSpecs: Record<SectionKey, Spec[]> = {
  personal: [
    { name: 'first_name', label: 'First Name', kind: 'text', placeholder: 'Enter first name', cols: 2 },
    { name: 'middle_name', label: 'Middle Name', kind: 'text', placeholder: 'Enter middle name', cols: 2, optional: true },
    { name: 'last_name', label: 'Last Name', kind: 'text', placeholder: 'Enter last name', cols: 2 },
    { name: 'date_of_birth', label: 'Date of Birth', kind: 'date', cols: 2 },
    { name: 'gender', label: 'Gender', kind: 'select', options: [{ value: 'male', label: 'Male' }, { value: 'female', label: 'Female' }, { value: 'non-binary', label: 'Non-binary' }, { value: 'other', label: 'Other' }, { value: 'prefer-not', label: 'Prefer not to say' }], cols: 2 },
    { name: 'blood_group', label: 'Blood Group', kind: 'select', options: [{ value: 'A+', label: 'A+' }, { value: 'A-', label: 'A-' }, { value: 'B+', label: 'B+' }, { value: 'B-', label: 'B-' }, { value: 'AB+', label: 'AB+' }, { value: 'AB-', label: 'AB-' }, { value: 'O+', label: 'O+' }, { value: 'O-', label: 'O-' }, { value: 'unknown', label: 'Unknown' }], cols: 2, optional: true },
    { name: 'nationality', label: 'Nationality', kind: 'text', placeholder: 'Enter nationality', cols: 2 },
    { name: 'ethnicity', label: 'Ethnicity', kind: 'text', placeholder: 'Enter ethnicity', cols: 2, optional: true },
    { name: 'country', label: 'Country', kind: 'text', placeholder: 'Enter country', cols: 2 },
    { name: 'state', label: 'State / Province', kind: 'text', placeholder: 'Enter state or province', cols: 2 },
    { name: 'city', label: 'City', kind: 'text', placeholder: 'Enter city', cols: 2 },
    { name: 'marital_status', label: 'Marital Status', kind: 'select', options: [{ value: 'single', label: 'Single' }, { value: 'married', label: 'Married' }, { value: 'divorced', label: 'Divorced' }, { value: 'widowed', label: 'Widowed' }, { value: 'separated', label: 'Separated' }], cols: 2, optional: true },
    { name: 'education_level', label: 'Education Level', kind: 'select', options: [{ value: 'high-school', label: 'High School' }, { value: 'bachelor', label: "Bachelor's Degree" }, { value: 'master', label: "Master's Degree" }, { value: 'doctorate', label: 'Doctorate' }, { value: 'professional', label: 'Professional Degree' }, { value: 'other', label: 'Other' }], cols: 2, optional: true },
    { name: 'occupation', label: 'Occupation', kind: 'text', placeholder: 'Enter occupation', cols: 2 },
    { name: 'industry', label: 'Industry', kind: 'text', placeholder: 'Enter industry', cols: 2, optional: true },
    { name: 'preferred_language', label: 'Preferred Language', kind: 'text', placeholder: 'Enter preferred language', cols: 2 },
    { name: 'email', label: 'Email Address', kind: 'text', type: 'email', placeholder: 'Enter email address', cols: 2 },
    { name: 'phone', label: 'Phone Number', kind: 'text', type: 'tel', placeholder: 'Enter phone number', cols: 2 },
    { name: 'emergency_contact', label: 'Emergency Contact Name', kind: 'text', placeholder: 'Enter emergency contact name', cols: 2, optional: true },
    { name: 'emergency_phone', label: 'Emergency Contact Phone', kind: 'text', type: 'tel', placeholder: 'Enter emergency phone', cols: 2, optional: true },
    { name: 'relationship', label: 'Relationship to Contact', kind: 'text', placeholder: 'e.g. Spouse, Parent', cols: 2, optional: true },
    { name: 'photo', label: 'Profile Photo', kind: 'photo', optional: true },
  ],
  body: [
    { name: 'height_cm', label: 'Height (cm)', kind: 'number', placeholder: 'e.g. 170', min: 50, max: 250, cols: 2 },
    { name: 'weight_kg', label: 'Weight (kg)', kind: 'number', placeholder: 'e.g. 70', min: 20, max: 300, cols: 2 },
    { name: 'waist_cm', label: 'Waist Circumference (cm)', kind: 'number', placeholder: 'e.g. 85', min: 30, max: 200, cols: 2, optional: true },
    { name: 'hip_cm', label: 'Hip Circumference (cm)', kind: 'number', placeholder: 'e.g. 95', min: 30, max: 200, cols: 2, optional: true },
    { name: 'body_fat_pct', label: 'Body Fat (%)', kind: 'number', placeholder: 'e.g. 18', min: 0, max: 60, cols: 2, optional: true, step: 0.1 },
    { name: 'muscle_pct', label: 'Muscle Mass (%)', kind: 'number', placeholder: 'e.g. 40', min: 0, max: 80, cols: 2, optional: true, step: 0.1 },
    { name: 'water_pct', label: 'Body Water (%)', kind: 'number', placeholder: 'e.g. 60', min: 0, max: 80, cols: 2, optional: true, step: 0.1 },
    { name: 'resting_heart_rate', label: 'Resting Heart Rate (bpm)', kind: 'number', placeholder: 'e.g. 72', min: 30, max: 200, cols: 2, optional: true },
    { name: 'blood_pressure_systolic', label: 'Blood Pressure Systolic (mmHg)', kind: 'number', placeholder: 'e.g. 120', min: 60, max: 250, cols: 2, optional: true },
    { name: 'blood_pressure_diastolic', label: 'Blood Pressure Diastolic (mmHg)', kind: 'number', placeholder: 'e.g. 80', min: 30, max: 150, cols: 2, optional: true },
    { name: 'body_temperature_c', label: 'Body Temperature (°C)', kind: 'number', placeholder: 'e.g. 36.6', min: 30, max: 45, cols: 2, optional: true, step: 0.1 },
    { name: 'oxygen_saturation_pct', label: 'Oxygen Saturation (%)', kind: 'number', placeholder: 'e.g. 98', min: 70, max: 100, cols: 2, optional: true },
    { name: 'blood_sugar_mgdl', label: 'Blood Sugar (mg/dL)', kind: 'number', placeholder: 'e.g. 90', min: 20, max: 600, cols: 2, optional: true },
    { name: 'hba1c_pct', label: 'HbA1c (%)', kind: 'number', placeholder: 'e.g. 5.5', min: 3, max: 20, cols: 2, optional: true, step: 0.1 },
  ],
  lifestyle: [
    { name: 'smoking', label: 'Smoking Status', kind: 'card', options: [{ value: 'never', label: 'Never' }, { value: 'former', label: 'Former Smoker' }, { value: 'current', label: 'Current Smoker' }], cols: 3 },
    { name: 'alcohol', label: 'Alcohol Consumption', kind: 'card', options: [{ value: 'none', label: 'None' }, { value: 'occasional', label: 'Occasional' }, { value: 'moderate', label: 'Moderate' }, { value: 'heavy', label: 'Heavy' }], cols: 4 },
    { name: 'drug_use', label: 'Recreational Drug Use', kind: 'chip', options: [{ value: 'never', label: 'Never' }, { value: 'former', label: 'Former' }, { value: 'current', label: 'Current' }], cols: 3, optional: true },
    { name: 'caffeine_intake', label: 'Caffeine Intake (cups/day)', kind: 'slider', min: 0, max: 10, step: 1, cols: 2, optional: true },
    { name: 'daily_water_intake', label: 'Daily Water Intake (glasses)', kind: 'slider', min: 0, max: 20, step: 1, cols: 2, optional: true },
    { name: 'screen_time', label: 'Daily Screen Time (hours)', kind: 'slider', min: 0, max: 24, step: 1, cols: 2, optional: true },
    { name: 'driving_hours', label: 'Daily Driving Hours', kind: 'slider', min: 0, max: 16, step: 1, cols: 2, optional: true },
  ],
  nutrition: [
    { name: 'diet_type', label: 'Diet Type', kind: 'card', options: [{ value: 'omnivore', label: 'Omnivore' }, { value: 'vegetarian', label: 'Vegetarian' }, { value: 'vegan', label: 'Vegan' }, { value: 'pescatarian', label: 'Pescatarian' }, { value: 'keto', label: 'Keto' }, { value: 'paleo', label: 'Paleo' }, { value: 'mediterranean', label: 'Mediterranean' }, { value: 'other', label: 'Other' }], cols: 4 },
    { name: 'meals_per_day', label: 'Meals Per Day', kind: 'slider', min: 1, max: 10, step: 1, cols: 2 },
    { name: 'fast_food_frequency', label: 'Fast Food Frequency', kind: 'chip', options: [{ value: 'never', label: 'Never' }, { value: 'rarely', label: 'Rarely' }, { value: 'monthly', label: 'Monthly' }, { value: 'weekly', label: 'Weekly' }, { value: 'daily', label: 'Daily' }], cols: 5 },
    { name: 'fruit_intake', label: 'Fruit Servings Per Day', kind: 'slider', min: 0, max: 15, step: 1, cols: 2 },
    { name: 'vegetable_intake', label: 'Vegetable Servings Per Day', kind: 'slider', min: 0, max: 15, step: 1, cols: 2 },
    { name: 'red_meat', label: 'Red Meat Intake', kind: 'chip', options: [{ value: 'never', label: 'Never' }, { value: 'rarely', label: 'Rarely' }, { value: 'weekly', label: 'Weekly' }, { value: 'daily', label: 'Daily' }], cols: 4, optional: true },
    { name: 'fish', label: 'Fish Intake', kind: 'chip', options: [{ value: 'never', label: 'Never' }, { value: 'monthly', label: 'Monthly' }, { value: 'weekly', label: 'Weekly' }, { value: 'daily', label: 'Daily' }], cols: 4, optional: true },
    { name: 'sugar_intake', label: 'Sugar Intake', kind: 'chip', options: [{ value: 'low', label: 'Low' }, { value: 'moderate', label: 'Moderate' }, { value: 'high', label: 'High' }], cols: 3, optional: true },
    { name: 'salt_intake', label: 'Salt Intake', kind: 'chip', options: [{ value: 'low', label: 'Low' }, { value: 'moderate', label: 'Moderate' }, { value: 'high', label: 'High' }], cols: 3, optional: true },
    { name: 'water_intake', label: 'Water Intake (glasses/day)', kind: 'slider', min: 0, max: 20, step: 1, cols: 2 },
    { name: 'food_allergies', label: 'Known Food Allergies', kind: 'textarea', placeholder: 'List any known food allergies', cols: 2, optional: true, rows: 3 },
    { name: 'supplements', label: 'Current Supplements', kind: 'textarea', placeholder: 'List any supplements you take', cols: 2, optional: true, rows: 3 },
  ],
  physical_activity: [
    { name: 'occupation_activity', label: 'Occupation Activity Level', kind: 'card', options: [{ value: 'sedentary', label: '🪑 Sedentary' }, { value: 'light', label: '🚶 Light' }, { value: 'moderate', label: '🏃 Moderate' }, { value: 'active', label: '💪 Active' }, { value: 'very_active', label: '⚡ Very Active' }], cols: 5 },
    { name: 'exercise_days', label: 'Exercise Days Per Week', kind: 'slider', min: 0, max: 7, step: 1, cols: 2 },
    { name: 'exercise_duration', label: 'Exercise Duration (min/session)', kind: 'slider', min: 0, max: 180, step: 5, cols: 2, optional: true },
    { name: 'exercise_types', label: 'Exercise Types', kind: 'chip', options: [{ value: 'running', label: '🏃 Running' }, { value: 'swimming', label: '🏊 Swimming' }, { value: 'cycling', label: '🚴 Cycling' }, { value: 'weight_training', label: '🏋️ Weights' }, { value: 'yoga', label: '🧘 Yoga' }, { value: 'walking', label: '🚶 Walking' }, { value: 'sports', label: '⚽ Sports' }, { value: 'dancing', label: '💃 Dancing' }], cols: 4, optional: true },
    { name: 'daily_step_count', label: 'Daily Step Count', kind: 'slider', min: 0, max: 50000, step: 1000, cols: 2, optional: true },
  ],
  sleep: [
    { name: 'avg_sleep_hours', label: 'Average Sleep Hours', kind: 'slider', min: 0, max: 24, step: 1, cols: 2 },
    { name: 'sleep_time', label: 'Typical Bedtime', kind: 'text', placeholder: 'e.g. 10:30 PM', cols: 2, optional: true },
    { name: 'wake_time', label: 'Typical Wake Time', kind: 'text', placeholder: 'e.g. 6:30 AM', cols: 2, optional: true },
    { name: 'snoring', label: 'Snoring', kind: 'emoji', options: [{ value: 'never', label: '😴 Never' }, { value: 'occasionally', label: '😪 Occasionally' }, { value: 'regularly', label: '😴 Regularly' }, { value: 'severe', label: '😱 Severe' }], cols: 4 },
    { name: 'sleep_apnea', label: 'Sleep Apnea', kind: 'emoji', options: [{ value: 'no', label: '😊 No' }, { value: 'suspected', label: '😐 Suspected' }, { value: 'diagnosed', label: '😟 Diagnosed' }], cols: 3 },
    { name: 'night_awakenings', label: 'Night Awakenings', kind: 'emoji', options: [{ value: 'none', label: '😴 None' }, { value: '1-2', label: '😪 1-2 times' }, { value: '3-4', label: '😴 3-4 times' }, { value: '5+', label: '😱 5+ times' }], cols: 4 },
    { name: 'daytime_sleepiness', label: 'Daytime Sleepiness', kind: 'emoji', options: [{ value: 'none', label: '😊 None' }, { value: 'mild', label: '😐 Mild' }, { value: 'moderate', label: '😴 Moderate' }, { value: 'severe', label: '😱 Severe' }], cols: 4 },
    { name: 'shift_worker', label: 'Shift Worker', kind: 'card', options: [{ value: 'no', label: '😴 No' }, { value: 'rotating', label: '🔄 Rotating' }, { value: 'night', label: '🌙 Night' }, { value: 'irregular', label: '⚡ Irregular' }], cols: 4 },
    { name: 'sleep_quality', label: 'Sleep Quality', kind: 'rating', min: 1, max: 5, cols: 2 },
  ],
  mental_health: [
    { name: 'stress_level', label: 'Stress Level', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'anxiety', label: 'Anxiety Level', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'depression_screening', label: 'Depression Screening', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'mood', label: 'Current Mood', kind: 'emoji', options: [{ value: 'good', label: '😊 Good' }, { value: 'fair', label: '😐 Fair' }, { value: 'low', label: '😔 Low' }, { value: 'very_low', label: '😢 Very Low' }], cols: 4 },
    { name: 'social_support', label: 'Social Support', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'meditation', label: 'Meditation Practice', kind: 'emoji', options: [{ value: 'daily', label: '🧘 Daily' }, { value: 'weekly', label: '📅 Weekly' }, { value: 'occasionally', label: '😐 Occasionally' }, { value: 'never', label: '❌ Never' }], cols: 4, optional: true },
    { name: 'mindfulness', label: 'Mindfulness Practice', kind: 'emoji', options: [{ value: 'daily', label: '🧘 Daily' }, { value: 'weekly', label: '📅 Weekly' }, { value: 'occasionally', label: '😐 Occasionally' }, { value: 'never', label: '❌ Never' }], cols: 4, optional: true },
    { name: 'work_life_balance', label: 'Work-Life Balance', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'burnout_risk', label: 'Burnout Risk', kind: 'rating', min: 1, max: 3, cols: 3 },
  ],
  conditions: [
    { name: 'surgeries_count', label: 'Number of Surgeries', kind: 'number', placeholder: 'e.g. 2', min: 0, max: 50, cols: 2, optional: true },
    { name: 'hospital_admissions', label: 'Hospital Admissions', kind: 'number', placeholder: 'e.g. 3', min: 0, max: 50, cols: 2, optional: true },
    { name: 'previous_fractures', label: 'Previous Fractures', kind: 'number', placeholder: 'e.g. 1', min: 0, max: 20, cols: 2, optional: true },
    { name: 'organ_transplants', label: 'Organ Transplants', kind: 'number', placeholder: 'e.g. 0', min: 0, max: 10, cols: 2, optional: true },
  ],
  surgeries: [],
  family_history: [
    { name: 'notes', label: 'General Notes', kind: 'textarea', placeholder: 'Any relevant family history notes', cols: 2, optional: true, rows: 3 },
  ],
  medications: [
    { name: 'current_status', label: 'Current Status', kind: 'select', options: [{ value: 'active', label: 'Active' }, { value: 'completed', label: 'Completed' }, { value: 'discontinued', label: 'Discontinued' }, { value: 'as_needed', label: 'As Needed' }], cols: 2, optional: true },
  ],
  allergies: [
    { name: 'type', label: 'Allergy Type', kind: 'select', options: [{ value: 'food', label: 'Food' }, { value: 'drug', label: 'Drug' }, { value: 'environmental', label: 'Environmental' }, { value: 'insect', label: 'Insect Sting' }, { value: 'latex', label: 'Latex' }, { value: 'other', label: 'Other' }], cols: 2 },
    { name: 'severity', label: 'Severity', kind: 'chip', options: [{ value: 'mild', label: 'Mild' }, { value: 'moderate', label: 'Moderate' }, { value: 'severe', label: 'Severe' }, { value: 'life_threatening', label: 'Life-Threatening' }], cols: 4 },
  ],
  vaccinations: [],
  women_health: [
    { name: 'pregnancy', label: 'Current Pregnancy', kind: 'emoji', options: [{ value: 'no', label: '😊 No' }, { value: 'planning', label: '🤔 Planning' }, { value: 'pregnant', label: '🤰 Pregnant' }, { value: 'postpartum', label: '🍼 Postpartum' }], cols: 4 },
    { name: 'menstrual_cycle', label: 'Menstrual Cycle Regularity', kind: 'card', options: [{ value: 'regular', label: 'Regular' }, { value: 'irregular', label: 'Irregular' }, { value: 'absent', label: 'Absent' }], cols: 3, optional: true },
    { name: 'pcos', label: 'PCOS', kind: 'emoji', options: [{ value: 'no', label: '😊 No' }, { value: 'diagnosed', label: '⚕️ Diagnosed' }, { value: 'suspected', label: '🔍 Suspected' }], cols: 3, optional: true },
    { name: 'menopause', label: 'Menopause', kind: 'emoji', options: [{ value: 'no', label: '😊 No' }, { value: 'perimenopause', label: '🔄 Perimenopause' }, { value: 'postmenopause', label: '🧓 Postmenopause' }], cols: 3, optional: true },
    { name: 'contraception', label: 'Contraception', kind: 'card', options: [{ value: 'none', label: 'None' }, { value: 'pill', label: '💊 Pill' }, { value: 'iud', label: '🩺 IUD' }, { value: 'implant', label: '💉 Implant' }, { value: 'injection', label: '💉 Injection' }, { value: 'other', label: 'Other' }], cols: 3, optional: true },
    { name: 'pregnancy_history', label: 'Pregnancy History', kind: 'textarea', placeholder: 'Gravida/Para details, complications', cols: 2, optional: true, rows: 3 },
  ],
  men_health: [
    { name: 'prostate_issues', label: 'Prostate Issues', kind: 'emoji', options: [{ value: 'no', label: '😊 No' }, { value: 'bph', label: '⚠️ BPH' }, { value: 'prostatitis', label: '🔬 Prostatitis' }, { value: 'cancer', label: '🚨 Cancer' }], cols: 4, optional: true },
    { name: 'testosterone_therapy', label: 'Testosterone Therapy', kind: 'card', options: [{ value: 'no', label: '😊 No' }, { value: 'current', label: '💉 Currently on therapy' }, { value: 'former', label: '📋 Former therapy' }], cols: 3, optional: true },
    { name: 'urinary_symptoms', label: 'Urinary Symptoms', kind: 'emoji', options: [{ value: 'none', label: '😊 None' }, { value: 'mild', label: '😐 Mild' }, { value: 'moderate', label: '😴 Moderate' }, { value: 'severe', label: '😱 Severe' }], cols: 4, optional: true },
  ],
  lifestyle_risks: [
    { name: 'seatbelt_use', label: 'Seatbelt Use', kind: 'card', options: [{ value: 'always', label: '✅ Always' }, { value: 'usually', label: '👍 Usually' }, { value: 'sometimes', label: '😐 Sometimes' }, { value: 'never', label: '❌ Never' }], cols: 4 },
    { name: 'helmet_use', label: 'Helmet Use (cycling/motorcycling)', kind: 'card', options: [{ value: 'always', label: '✅ Always' }, { value: 'usually', label: '👍 Usually' }, { value: 'sometimes', label: '😐 Sometimes' }, { value: 'never', label: '❌ Never' }], cols: 4, optional: true },
    { name: 'sun_exposure', label: 'Sun Exposure Level', kind: 'card', options: [{ value: 'low', label: '🌤 Low' }, { value: 'moderate', label: '☀️ Moderate' }, { value: 'high', label: '🔥 High' }, { value: 'very_high', label: '☠️ Very High' }], cols: 4 },
    { name: 'driving_habits', label: 'Driving Habits', kind: 'card', options: [{ value: 'safe', label: '🛡 Safe driver' }, { value: 'moderate', label: '😐 Moderate' }, { value: 'risky', label: '⚠️ Risky (speeding, etc.)' }], cols: 3, optional: true },
    { name: 'firearms', label: 'Firearms in Household', kind: 'card', options: [{ value: 'no', label: '✅ No' }, { value: 'yes_stored', label: '🔒 Yes, securely stored' }, { value: 'yes_unstored', label: '⚠️ Yes, not securely stored' }], cols: 3, optional: true },
    { name: 'occupational_hazards', label: 'Occupational Hazards', kind: 'textarea', placeholder: 'Describe any occupational hazards', cols: 2, optional: true, rows: 2 },
    { name: 'substance_exposure', label: 'Substance Exposure', kind: 'chip', options: [{ value: 'none', label: 'None' }, { value: 'chemical', label: '🧪 Chemical' }, { value: 'biological', label: '🦠 Biological' }, { value: 'radiation', label: '☢️ Radiation' }, { value: 'other', label: 'Other' }], cols: 5, optional: true },
  ],
  environment: [
    { name: 'air_pollution', label: 'Air Pollution Exposure', kind: 'card', options: [{ value: 'low', label: '🌤 Low' }, { value: 'moderate', label: '😐 Moderate' }, { value: 'high', label: '🔥 High' }], cols: 3 },
    { name: 'water_source', label: 'Water Source', kind: 'card', options: [{ value: 'municipal', label: '🏙 Municipal/Treated' }, { value: 'well', label: '🪣 Well Water' }, { value: 'bottled', label: '🧴 Bottled' }, { value: 'other', label: 'Other' }], cols: 4 },
    { name: 'home_type', label: 'Home Type', kind: 'card', options: [{ value: 'apartment', label: '🏢 Apartment' }, { value: 'house', label: '🏠 Single-family home' }, { value: 'townhouse', label: '🏘 Townhouse' }, { value: 'rural', label: '🌾 Rural property' }], cols: 4 },
    { name: 'pets', label: 'Pets at Home', kind: 'card', options: [{ value: 'none', label: '🐕 None' }, { value: 'dog', label: '🐶 Dog(s)' }, { value: 'cat', label: '🐱 Cat(s)' }, { value: 'bird', label: '🐦 Bird(s)' }, { value: 'other', label: 'Other' }], cols: 5, optional: true },
    { name: 'mold_exposure', label: 'Mold Exposure', kind: 'card', options: [{ value: 'no', label: '✅ No' }, { value: 'suspected', label: '🔍 Suspected' }, { value: 'confirmed', label: '⚠️ Confirmed' }], cols: 3, optional: true },
    { name: 'chemical_exposure', label: 'Chemical Exposure', kind: 'card', options: [{ value: 'none', label: '✅ None' }, { value: 'household', label: '🏠 Household chemicals' }, { value: 'industrial', label: '🏭 Industrial' }, { value: 'agricultural', label: '🌾 Agricultural' }], cols: 4, optional: true },
    { name: 'noise_pollution', label: 'Noise Pollution', kind: 'slider', min: 1, max: 10, step: 1, cols: 2, optional: true },
  ],
  occupation: [
    { name: 'industry', label: 'Industry', kind: 'text', placeholder: 'e.g. Healthcare, Construction', cols: 2 },
    { name: 'working_hours', label: 'Working Hours Per Week', kind: 'slider', min: 0, max: 80, step: 1, cols: 2 },
    { name: 'night_shifts', label: 'Night Shifts', kind: 'card', options: [{ value: 'no', label: '😴 No' }, { value: 'occasional', label: '🌙 Occasional' }, { value: 'regular', label: '🔄 Regular' }, { value: 'rotating', label: '⚡ Rotating' }], cols: 4 },
    { name: 'travel_frequency', label: 'Travel Frequency', kind: 'card', options: [{ value: 'none', label: '🏠 None' }, { value: 'occasional', label: '✈️ Occasional' }, { value: 'frequent', label: '🛫 Frequent' }, { value: 'constant', label: '🌍 Constant' }], cols: 4, optional: true },
    { name: 'heavy_lifting', label: 'Heavy Lifting', kind: 'card', options: [{ value: 'none', label: '✅ None' }, { value: 'occasional', label: '😐 Occasional' }, { value: 'frequent', label: '💪 Frequent' }, { value: 'daily', label: '🏋️ Daily' }], cols: 4, optional: true },
    { name: 'work_stress', label: 'Work Stress Level', kind: 'rating', min: 1, max: 5, cols: 2 },
    { name: 'work_environment', label: 'Work Environment', kind: 'card', options: [{ value: 'office', label: '🏢 Office/Indoor' }, { value: 'outdoor', label: '🌳 Outdoor' }, { value: 'mixed', label: '🔀 Mixed' }, { value: 'hazardous', label: '⚠️ Hazardous' }], cols: 4, optional: true },
  ],
  travel: [
    { name: 'countries_visited', label: 'Countries Visited', kind: 'textarea', placeholder: 'List countries visited in the last 5 years', cols: 2, optional: true, rows: 2 },
    { name: 'tropical_regions', label: 'Tropical Regions Visited', kind: 'textarea', placeholder: 'List tropical regions visited', cols: 2, optional: true, rows: 2 },
    { name: 'vaccinations_required', label: 'Vaccinations Required for Travel', kind: 'textarea', placeholder: 'List required vaccinations', cols: 2, optional: true, rows: 2 },
    { name: 'recent_travel', label: 'Recent Travel (last 6 months)', kind: 'textarea', placeholder: 'Describe recent travel', cols: 2, optional: true, rows: 2 },
  ],
  emergency: [
    { name: 'primary_name', label: 'Primary Contact Name', kind: 'text', placeholder: 'Enter full name', cols: 2 },
    { name: 'primary_phone', label: 'Primary Contact Phone', kind: 'text', type: 'tel', placeholder: 'Enter phone number', cols: 2 },
    { name: 'primary_relationship', label: 'Relationship', kind: 'card', options: [{ value: 'spouse', label: '💑 Spouse' }, { value: 'parent', label: '👨 Parent' }, { value: 'child', label: '👧 Child' }, { value: 'sibling', label: '👥 Sibling' }, { value: 'friend', label: '🤝 Friend' }, { value: 'other', label: '📌 Other' }], cols: 3 },
    { name: 'secondary_name', label: 'Secondary Contact Name', kind: 'text', placeholder: 'Enter full name', cols: 2, optional: true },
    { name: 'secondary_phone', label: 'Secondary Contact Phone', kind: 'text', type: 'tel', placeholder: 'Enter phone number', cols: 2, optional: true },
    { name: 'secondary_relationship', label: 'Relationship', kind: 'card', options: [{ value: 'spouse', label: '💑 Spouse' }, { value: 'parent', label: '👨 Parent' }, { value: 'child', label: '👧 Child' }, { value: 'sibling', label: '👥 Sibling' }, { value: 'friend', label: '🤝 Friend' }, { value: 'other', label: '📌 Other' }], cols: 3, optional: true },
    { name: 'hospital_preference', label: 'Hospital Preference', kind: 'text', placeholder: 'Enter preferred hospital', cols: 2, optional: true },
    { name: 'insurance_provider', label: 'Insurance Provider', kind: 'text', placeholder: 'Enter insurance provider', cols: 2, optional: true },
    { name: 'organ_donor', label: 'Organ Donor', kind: 'card', options: [{ value: 'yes', label: '✅ Yes' }, { value: 'no', label: '❌ No' }, { value: 'unknown', label: '❓ Unknown' }], cols: 3 },
  ],
  consents: [
    { name: 'terms_accepted', label: 'I accept the terms and conditions', kind: 'checkbox' },
    { name: 'ai_consent', label: 'I consent to AI-assisted health analysis', kind: 'checkbox' },
    { name: 'research_consent', label: 'I consent to anonymized research use of my data', kind: 'checkbox' },
  ],
}
