import type { AssessmentDef, AssessmentStatus, AIPriority, Difficulty, HealthScorePoint, AIInsight, TimelineItem } from './types'

export const bodySystems = [
  { id: 'cardiovascular', name: 'Cardiovascular', icon: 'heart-pulse', colorHex: '#ef4444' },
  { id: 'respiratory', name: 'Respiratory', icon: 'wind', colorHex: '#3b82f6' },
  { id: 'endocrine', name: 'Endocrine', icon: ' activity', colorHex: '#a855f7' },
  { id: 'neurological', name: 'Neurological', icon: 'brain', colorHex: '#f59e0b' },
  { id: 'renal', name: 'Renal', icon: 'kidney', colorHex: '#14b8a8' },
  { id: 'hepatic', name: 'Liver', icon: 'liver', colorHex: '#eab308' },
  { id: 'gastrointestinal', name: 'Digestive', icon: 'utensils', colorHex: '#84cc16' },
  { id: 'mental', name: 'Mental Health', icon: 'brain-circuit', colorHex: '#8b5cf6' },
  { id: 'musculoskeletal', name: 'Musculoskeletal', icon: 'bone', colorHex: '#d97706' },
  { id: 'ocular', name: 'Ocular', icon: 'eye', colorHex: '#06b6d4' },
  { id: 'lifestyle', name: 'Lifestyle', icon: 'smiling', colorHex: '#10b981' },
  { id: 'preventive', name: 'Preventive Screening', icon: 'shield-check', colorHex: '#6366f1' },
  { id: 'women', name: "Women's Health", icon: 'woman', colorHex: '#ec4899' },
  { id: 'men', name: "Men's Health", icon: 'man', colorHex: '#3b82f6' },
  { id: 'nutrition', name: 'Nutrition', icon: 'apple', colorHex: '#16a34a' },
  { id: 'oncology', name: 'Oncology', icon: 'scan-scan', colorHex: '#dc2626' },
]

export const assessmentDefs: AssessmentDef[] = [
  {
    id: 'general-health',
    slug: 'general-health-assessment',
    title: 'General Health Assessment',
    description: 'A comprehensive overview of your overall health and wellness.',
    icon: 'clipboard-text',
    gradient: 'from-indigo-500 to-blue-500',
    durationMinutes: 12,
    questionsCount: 48,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[0], bodySystems[1], bodySystems[6], bodySystems[7]],
    riskCategories: ['Chronic disease', 'Wellness gaps'],
    recommendedFrequency: 'Every 6 months',
    aiEnabled: true,
    priority: 'high',
    status: 'recommended',
    progressPct: 0,
    healthScore: 84,
  },
  {
    id: 'heart-health',
    slug: 'heart-health',
    title: 'Heart Health',
    description: 'Evaluate cardiovascular risk factors and heart disease markers.',
    icon: 'heart',
    gradient: 'from-rose-500 to-pink-500',
    durationMinutes: 8,
    questionsCount: 32,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[0]],
    riskCategories: ['Cardiovascular disease', 'Hypertension'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'high',
    status: 'in_progress',
    progressPct: 68,
    lastSaved: '2 hours ago',
    healthScore: 76,
  },
  {
    id: 'kidney-health',
    slug: 'kidney-health',
    title: 'Kidney Health',
    description: 'Assess kidney function and risk of chronic kidney disease.',
    icon: 'kidney',
    gradient: 'from-teal-500 to-emerald-500',
    durationMinutes: 6,
    questionsCount: 24,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[4]],
    riskCategories: ['Kidney disease', 'Diabetes'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'completed',
    progressPct: 100,
    completedDate: '2026-07-12',
    healthScore: 91,
    version: 'v2.1',
    doctorReviewed: true,
  },
  {
    id: 'diabetes-risk',
    slug: 'diabetes-risk',
    title: 'Diabetes Risk',
    description: 'Identify risk factors and early markers for diabetes.',
    icon: 'needle',
    gradient: 'from-amber-500 to-orange-500',
    durationMinutes: 5,
    questionsCount: 20,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[2]],
    riskCategories: ['Type 2 diabetes'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'completed',
    progressPct: 100,
    completedDate: '2026-05-30',
    healthScore: 88,
    version: 'v2.1',
    doctorReviewed: false,
  },
  {
    id: 'hypertension',
    slug: 'hypertension',
    title: 'Hypertension Risk',
    description: 'Screen for high blood pressure risk and lifestyle contributors.',
    icon: 'gauge',
    gradient: 'from-cyan-500 to-blue-500',
    durationMinutes: 4,
    questionsCount: 16,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[0]],
    riskCategories: ['Hypertension', 'Cardiovascular disease'],
    recommendedFrequency: 'Every 6 months',
    aiEnabled: true,
    priority: 'medium',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'mental-wellness',
    slug: 'mental-wellness',
    title: 'Mental Wellness',
    description: 'Gauge stress, mood, and mental wellbeing indicators.',
    icon: 'smile',
    gradient: 'from-purple-500 to-indigo-500',
    durationMinutes: 7,
    questionsCount: 28,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[7]],
    riskCategories: ['Depression', 'Anxiety', 'Stress'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'high',
    status: 'locked',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'respiratory-health',
    slug: 'respiratory-health',
    title: 'Respiratory Health',
    description: 'Assess lung function and breathing-related risk factors.',
    icon: 'wind',
    gradient: 'from-green-400 to-emerald-600',
    durationMinutes: 5,
    questionsCount: 18,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[1]],
    riskCategories: ['Asthma', 'COPD'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'cancer-screening',
    slug: 'cancer-screening',
    title: 'Cancer Screening',
    description: 'Age- and risk-appropriate cancer screening recommendations.',
    icon: 'scan',
    gradient: 'from-fuchsia-500 to-pink-600',
    durationMinutes: 9,
    questionsCount: 36,
    difficulty: 'Advanced',
    bodySystems: [bodySystems[15]],
    riskCategories: ['Multiple cancers'],
    recommendedFrequency: 'Annual or biennial',
    aiEnabled: true,
    priority: 'high',
    status: 'recommended',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'womens-health',
    slug: 'womens-health',
    title: "Women's Health",
    description: 'Reproductive and hormonal health assessment.',
    icon: 'female',
    gradient: 'from-pink-500 to-rose-500',
    durationMinutes: 8,
    questionsCount: 30,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[13]],
    riskCategories: ['Hormonal imbalance', 'Bone health'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'mens-health',
    slug: 'mens-health',
    title: "Men's Health",
    description: "Prostate, hormonal, and overall men's health screening.",
    icon: 'male',
    gradient: 'from-blue-500 to-indigo-500',
    durationMinutes: 8,
    questionsCount: 28,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[14]],
    riskCategories: ['Prostate health', 'Testosterone'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'nutrition',
    slug: 'nutrition-assessment',
    title: 'Nutrition Assessment',
    description: 'Evaluate dietary habits and nutritional risk.',
    icon: 'apple',
    gradient: 'from-lime-400 to-green-600',
    durationMinutes: 6,
    questionsCount: 22,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[12]],
    riskCategories: ['Malnutrition', 'Obesity'],
    recommendedFrequency: 'Every 6 months',
    aiEnabled: true,
    priority: 'medium',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'lifestyle',
    slug: 'lifestyle-assessment',
    title: 'Lifestyle Assessment',
    description: 'Analyze activity, sleep, and daily habit patterns.',
    icon: 'bed',
    gradient: 'from-sky-400 to-cyan-600',
    durationMinutes: 6,
    questionsCount: 24,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[10]],
    riskCategories: ['Poor sleep', 'Sedentary lifestyle'],
    recommendedFrequency: 'Every 3 months',
    aiEnabled: true,
    priority: 'low',
    status: 'expired',
    progressPct: 0,
    healthScore: 0,
    doctorReviewed: false,
  },
  {
    id: 'exercise-fitness',
    slug: 'exercise-fitness',
    title: 'Exercise & Fitness',
    description: 'Physical activity and fitness capacity screening.',
    icon: 'dumbbell',
    gradient: 'from-orange-400 to-amber-600',
    durationMinutes: 5,
    questionsCount: 18,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[8]],
    riskCategories: ['Low fitness'],
    recommendedFrequency: 'Every 6 months',
    aiEnabled: false,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'sleep',
    slug: 'sleep-assessment',
    title: 'Sleep Assessment',
    description: 'Evaluate sleep quality and disorders.',
    icon: 'moon',
    gradient: 'from-indigo-400 to-purple-700',
    durationMinutes: 4,
    questionsCount: 15,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[7]],
    riskCategories: ['Sleep apnea', 'Insomnia'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'digestive',
    slug: 'digestive-health',
    title: 'Digestive Health',
    description: 'Gut health, digestion, and dietary tolerance review.',
    icon: 'heart-hand',
    gradient: 'from-yellow-400 to-amber-600',
    durationMinutes: 7,
    questionsCount: 26,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[6]],
    riskCategories: ['IBD', 'GERD'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'neurological',
    slug: 'neurological-assessment',
    title: 'Neurological Assessment',
    description: 'Cognitive function and neurological symptom screening.',
    icon: 'brain',
    gradient: 'from-red-500 to-rose-600',
    durationMinutes: 9,
    questionsCount: 34,
    difficulty: 'Advanced',
    bodySystems: [bodySystems[3]],
    riskCategories: ['Cognitive decline', 'Headache'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'recommended',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'bone-joint',
    slug: 'bone-joint-health',
    title: 'Bone & Joint Health',
    description: 'Musculoskeletal and joint health evaluation.',
    icon: 'bone',
    gradient: 'from-stone-400 to-slate-700',
    durationMinutes: 6,
    questionsCount: 22,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[8]],
    riskCategories: ['Osteoporosis', 'Arthritis'],
    recommendedFrequency: 'Annually',
    aiEnabled: false,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'eye-health',
    slug: 'eye-health',
    title: 'Eye Health',
    description: 'Vision and ocular health screening.',
    icon: 'eye',
    gradient: 'from-teal-400 to-cyan-700',
    durationMinutes: 4,
    questionsCount: 14,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[9]],
    riskCategories: ['Glaucoma', 'Macular degeneration'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'liver-health',
    slug: 'liver-health',
    title: 'Liver Health',
    description: 'Hepatic function and liver disease risk screening.',
    icon: 'liver',
    gradient: 'from-amber-400 to-orange-700',
    durationMinutes: 6,
    questionsCount: 20,
    difficulty: 'Intermediate',
    bodySystems: [bodySystems[5]],
    riskCategories: ['Fatty liver', 'Hepatitis'],
    recommendedFrequency: 'Annually',
    aiEnabled: true,
    priority: 'medium',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
  {
    id: 'immune',
    slug: 'immune-health',
    title: 'Immune Health',
    description: 'Immune function and infection susceptibility review.',
    icon: 'shield',
    gradient: 'from-violet-500 to-purple-700',
    durationMinutes: 5,
    questionsCount: 18,
    difficulty: 'Beginner',
    bodySystems: [bodySystems[14]],
    riskCategories: ['Immunodeficiency', 'Infections'],
    recommendedFrequency: 'Every 6 months',
    aiEnabled: true,
    priority: 'low',
    status: 'not_started',
    progressPct: 0,
    healthScore: 0,
  },
] satisfies AssessmentDef[]

export const userAssessments: AssessmentDef[] = assessmentDefs

export const timelineEvents: TimelineItem[] = [
  { id: 't1', type: 'completed', title: 'General Health Assessment completed', meta: 'Score: 84', date: '2026-07-12 09:32', icon: 'clipboard-text', iconBg: 'bg-emerald-500' },
  { id: 't2', type: 'started', title: 'Heart Health assessment started', meta: '', date: '2026-07-05 14:48', icon: 'heart', iconBg: 'bg-indigo-500' },
  { id: 't3', type: 'profile', title: 'Profile completed & updated', meta: '8 sections', date: '2026-06-30 11:15', icon: 'user', iconBg: 'bg-cyan-500' },
  { id: 't4', type: 'lab', title: 'Laboratory results added', meta: 'CMP + Lipid Panel', date: '2026-06-22 10:00', icon: 'test-tube', iconBg: 'bg-amber-500' },
  { id: 't5', type: 'rec', title: 'Recommendations generated', meta: '3 new', date: '2026-06-22 10:05', icon: 'lightbulb', iconBg: 'bg-fuchsia-500' },
  { id: 't6', type: 'ai', title: 'AI report generated', meta: 'Kidney Health', date: '2026-05-30 16:20', icon: 'bot', iconBg: 'bg-purple-500' },
]

export const healthScoreTrend: HealthScorePoint[] = [
  { date: 'Jan', score: 64 },
  { date: 'Feb', score: 68 },
  { date: 'Mar', score: 71 },
  { date: 'Apr', score: 75 },
  { date: 'May', score: 78 },
  { date: 'Jun', score: 82 },
  { date: 'Jul', score: 84 },
]

export const aiInsight: AIInsight = {
  currentHealthScore: 84,
  riskTrend: 'improving',
  mostImproved: 'Neurological',
  highestRisk: 'Cardiovascular',
  confidence: 87,
  lastAIUpdate: '2 hours ago',
}

export const completedAssessments = assessmentDefs.filter((a) => a.status === 'completed')

export const assessmentCategories = [
  { id: 'general', title: 'General', icon: 'clipboard-text', gradient: 'from-indigo-500 to-blue-500', count: 1 },
  { id: 'cardiovascular', title: 'Cardiovascular', icon: 'heart', gradient: 'from-rose-500 to-pink-500', count: 3 },
  { id: 'respiratory', title: 'Respiratory', icon: 'wind', gradient: 'from-green-400 to-emerald-600', count: 1 },
  { id: 'endocrine', title: 'Endocrine', icon: 'activity', gradient: 'from-purple-500 to-indigo-500', count: 1 },
  { id: 'neurology', title: 'Neurology', icon: 'brain', gradient: 'from-red-500 to-rose-600', count: 1 },
  { id: 'kidneys', title: 'Kidneys', icon: 'kidney', gradient: 'from-teal-500 to-emerald-500', count: 1 },
  { id: 'liver', title: 'Liver', icon: 'liver', gradient: 'from-amber-400 to-orange-700', count: 1 },
  { id: 'digestive', title: 'Digestive', icon: 'heart-hand', gradient: 'from-yellow-400 to-amber-600', count: 1 },
  { id: 'mental', title: 'Mental Health', icon: 'brain-circuit', gradient: 'from-purple-500 to-indigo-500', count: 1 },
  { id: 'lifestyle', title: 'Lifestyle', icon: 'bed', gradient: 'from-sky-400 to-cyan-600', count: 2 },
  { id: 'nutrition', title: 'Nutrition', icon: 'apple', gradient: 'from-lime-400 to-green-600', count: 1 },
  { id: 'cancer', title: 'Cancer Screening', icon: 'scan', gradient: 'from-fuchsia-500 to-pink-600', count: 1 },
  { id: 'womens', title: "Women's Health", icon: 'female', gradient: 'from-pink-500 to-rose-500', count: 1 },
  { id: 'mens', title: "Men's Health", icon: 'male', gradient: 'from-blue-500 to-indigo-500', count: 1 },
  { id: 'preventive', title: 'Preventive Screening', icon: 'shield-check', gradient: 'from-fuchsia-500 to-pink-600', count: 1 },
]

export const recommendationInsight = {
  title: 'Neurological Assessment',
  reason: 'Your General Health score suggests gaps in cognitive & neurological health data.',
  priority: 'high' as AIPriority,
  riskReduction: '22%',
  suggestedDate: '2026-08-15',
  gradient: 'from-red-500 to-rose-600',
}

export type { AssessmentStatus, AIPriority, Difficulty, HealthScorePoint, AIInsight, TimelineItem }
